DROP SECURITY POLICY IF EXISTS ClientAccessPolicy
GO
DROP TABLE IF EXISTS Company
GO
ALTER TABLE Product
SET (SYSTEM_VERSIONING=OFF)
GO
DROP TABLE IF EXISTS Product
GO
DROP TABLE IF EXISTS History.Product
GO
DROP SCHEMA IF EXISTS History